//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TareaEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int id_pedido { get; set; }
        public System.DateTime fecha { get; set; }
        public string nombre_cliente { get; set; }
        public int monto_pedido { get; set; }
        public int id_distrito { get; set; }
    
        public virtual Distrito Distrito { get; set; }
    }
}
